--- # My users
- hosts: appserver
  user: test
  sudo: yes
  gather_facts: yes
  tasks:
   - name: creating users
     user: name={{item}} state=present
     with_items:
       - test1
       - test2
       - test3
       - test4
   - name: Install Apache package
     command: yum -y install httpd
     when: ansible_os_family == "RedHat"
   - name: Install Apache package 
     command: apt-get -y install apache2
     when: ansible_os_family == "Debian" 
    
     
